### ISSUE TITLE
What was it like to learn Lua?

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/lua#250]
We’ve recently [started a project](https://exercism.io/blog/redesigning-tracks-in-partnership-with-chicago-university-and-sloan-foundation) to find the best way to design our tracks, in order to optimize the learning experience of students.

As a first step, we’ll be [examining the ways in which languages are unique and the ways in which they are similar](https://github.com/exercism/exercism/issues/5059). For this, we’d really like to use the knowledge of **everyone** involved in the Exercism community (students, mentors, maintainers) to answer the following questions:

1. How was your experience learning Lua? What was helpful while learning Lua? What did you struggle with? How did you tackle problems?
1. In what ways did Lua differ from other languages you knew at the time? What was hard to learn? What did you have to unlearn? What syntax did you have to remap? What concepts carried over nicely?

Could you spare 5 minutes to help us by answering these questions? It would greatly help us improve the experience students have learning Lua :)

_Note: this issue is **not** meant as a discussion, just as a place for people to post their own, personal experiences._

_Want to keep your thoughts private but still help? Feel free to email me at erik@exercism.io_

Thank you!

**Comment by ryanplusplus** [comment]
> How was your experience learning Lua? What was helpful while learning Lua? What did you struggle with? How did you tackle problems?

I learned Lua after I had already learned several other languages. I learned it primarily by reading Programming in Lua, the canonical book on the language, the libraries, and the C API. It's very short by comparison to the equivalent material in other languages and includes a lot of great exercises for deepening your understanding. My primary struggles were learning how to effectively use the table type and how to solve problems in a way that took advantage of Lua's unique features. When I ran into problems, Stack Overflow and the Lua reference manual (thankfully also short) were generally all I needed.

> In what ways did Lua differ from other languages you knew at the time? What was hard to learn? What did you have to unlearn? What syntax did you have to remap? What concepts carried over nicely?

Lua was mostly different in its radical simplicity. It took me a while to wrap my head around all of the ways to use tables to solve problems, but otherwise I found it rather natural. Despite being a language I learned relatively late, I started to think in Lua very quickly and wouldn't say I needed to remap a lot of concepts; Instead, I feel that Lua allowed me to think about concepts I already understood in a simpler and more intuitive way with fewer non-essential distractions.

**Comment by imolein** [comment]
> How was your experience learning Lua? What was helpful while learning Lua? What did you struggle with? How did you tackle problems?

As a Sysadmin I know my swiss army knife Bash, resp. POSIX shell, but I also wanted to learn a real programming language for quite some time. I looked into the languages I already had contact with, like Perl or Python, but lost the interest in learning one of them pretty quickly. Some day I read about the XMPP Server Prosody and that it is written in Lua, a language I never heard of. I looked into it's source code and instantly wanted to learn this simple and beautiful looking language. I ordered the latest version of the Programming in Lua book and started reading. As someone with limited prior knowledge to the whole programming topic the book was surprisingly easy to read and most importantly, to understand. So I learned the language basically by reading it, doing the exercises from it and after someone mentioned exercism, I started doing exercises there too. ;) I struggled the most understanding this Metatable/Metamethods topic, but after reading other modules, some help from SO, the reference manual and a lot of trial and error I got it into my head.

> In what ways did Lua differ from other languages you knew at the time? What was hard to learn? What did you have to unlearn? What syntax did you have to remap? What concepts carried over nicely?

Since I didn't deeply know another programming language before I learned Lua, I didn't have to unlearn or wrap my head around things. And compared to Bash, everything was more understandable and clear anyway. :D But now, that I also have basic knowledge of Python, I still like Lua more, because of it's minimalism, simplicity and flexiblilty. (and I prefer do...end over indentation style :) )

**Comment by iHiD** [comment]
Thanks both!

**Comment by ErikSchierboom** [comment]
We're closing this issue as it was part of our research for the v3 version of Exercism which has [just been released](https://exercism.org/blog/exercism-v3-has-launched).

Thanks everyone for chipping in! It has been greatly appreciated.
